name: Events demo
on :
   pull_request:
     types:
      - opened
     branches:
        - main
        - 'dev-*'
        - feature/**'
 env:
   Mango_DbName:hello ## providing values for the variable db name and this will be used for entire workflow unles and until we override in the job level
   workflow_dispatch:
 ##this will trigger only to main and dev branches whenever push happend  
   Push:
     branches:
        - main
        - 'dev-*'
        - feature/**'#this ** is used for "/" like feature/new-start/ like this
jobs:
  build:
    env:
      Mango_DB_user: name of the sb use ## we can provide any thing as a value
    runs-on: ubuntu-latest
    outputs:
      script-file
    steps:
      - name: Output the event data
        run: echo "${{ toJson (github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json) }}
      - name: Install dependies
        run: npm ci
      - name: test the code
        run: npm run the test
      - name: build teh code
        run: npm run the build
      - name: publish JS Filename
        run: find path to the filename/*.Json -type f -execdir echo 'script-file{}' ';'## this is a linux xommand inorder to get the file name
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
           name: dest-files #we can give file name
           path: | ## For multiple we can use this symbol
              dist
              vanaja.json
      - name: deploy the code
          needs: build
         runs-on: ubuntu-latest
         steps:
         - name: Get the artifacts
           uses: actions/download-artifact@v3 ##nthng but we are downloading the artifacts to here
           with:
             name: dest-files ###this could be same what we uploading we mentioned in deploy details
           -name: output the contents
            run: ls
         - name:deploy  
           run: echo "deploying the code"
        
        

