name: Events demo
on :
   pull_request:
     types:
      - opened
     branches:
        - main
        - 'dev-*'
        - feature/**' 
   workflow_dispatch:
 ##this will trigger only to main and dev branches whenever push happend  
   Push:
     branches:
        - main
        - 'dev-*'
        - feature/**'#this ** is used for "/" like feature/new-start/ like this
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output the event data
        run: echo "${{ toJson (github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependies
        run: npm ci
      - name: test the code
        run: npm run the test
      - name: build teh code
        run: npm run the build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
           name: dest-files #we can give file name
           path: | ## For multiple we can use this symbol
              dist
              vanaja.json
      - name: deploy the code
        run: echo "deploying the code"
        
        

